### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by blittle** [CanopyTax/sofe#6]
@joeldenning is it `Sofe`, `sofe`, or `SOFE`?

**Comment by joeldenning** [comment]
Good question. I'm not a fan of `SOFE`, but am conflicted between the other two. Most other projects seem to capitalize when writing docs, but not capitalize in code. Especially when the project has a one-word name that is in the dictionary. In our case, it's just an acronym, not a dictionary word. So I feel we really could go either way. The lazy/KISS side of me leans a bit towards `sofe` so that you never have to worry about which situation to capitalize/not capitalize. And a good precedent for it is that [npm *always* is lowercase even at the beginning of a sentence](https://docs.npmjs.com/getting-started/what-is-npm).

What are your thoughts?

Also, not to throw a wrench in things, but what are your thoughts on `sofea`? Service Oriented Front-End Architecture. [Google searching](https://www.google.com/search?q=sofea) reveals that some other people have already come up with the acronym as a concept, but my reasons for liking it are mostly about pronunciation.

**Comment by blittle** [comment]
I generally like sofe. Either way it should be consistent. A few weeks ago
I Google searched service oriented front end architecture. From what I
found, it seemed people were more taking about componentization and MVC. We
will probably have a hard enough time helping people understand the
difference between shared libs and services it might be good to be
different from sofea?

**Comment by joeldenning** [comment]
sounds good. `sofe` it is.

**Comment by blittle** [comment]
Curious did you find anything sofea related that was more than
componentization and MVC?

**Comment by blittle** [comment]
Fixed with https://github.com/CanopyTax/sofe/commit/ba47b53911a26666823f19b377f77a1d9a3936d4

**Comment by joeldenning** [comment]
No, sofea seems to originate from http://www.smart-soft.com/downloads/articles/Life-above-the-Service-Tier-v1_1.pdf, which is definitely client side componentization and MVC.
